### ISSUE TITLE
422 on Products

### ISSUE THREAD

**Issue by calebcurtis8** [workwithpact/StoreDuplicator#2]
After running `yarn start --products` each product fails to import to an empty destination store and there is a http 422 error which I can see after adding a console log. I double checked the permissions on both stores and `yarn start` returns "Store configuration looks correct."

I'm guessing there's an issue with line 174 of migrator.js and the structure of the product object
`const newProduct = await this.destination.product.create(product)`

**Comment by alexleclair** [comment]
Have you tried it more than once? We've seen a few images fail over time, breaking the product import. Running it a second time might do the trick, and wouldn't import already-imported products

**Comment by calebcurtis8** [comment]
Yes, I've only tried it on one source store though, and it's failing on every product. 
![Image 2021-03-11 at 12 54 56 PM](https://user-images.githubusercontent.com/6586334/110832304-28a4d480-8269-11eb-8a43-3bc60f5d8af8.jpg)

**Comment by calebcurtis8** [comment]
Perhaps it is related to the number of metafields on these products or the content within them, from another store with less metafields I am not having that problem.

**Comment by alexleclair** [comment]
(Sorry, I somehow did not get a notification when you answered!)
Interesting; The amount of metafields shouldn't matter. Do these products have anything in common (ex: are they gift cards?).
Creating gift cards through the API is currently not supported, so that could explain it...

**Comment by calebcurtis8** [comment]
I was curious if it was the metafields that are filled by Okendo (reviews app) that have HTML and are super long, but ignoring them/all the metafields did not resolve the issue.
I was able to duplicate the products from one store, but not another. I’ll keep trying to hunt down what is triggering the 422 entity not processed error.
I see that gift cards aren’t working, but in this case it seems to be more all products or none are working. Collections are working fine…
I’ve seen that there could be issues with particular values triggering this error, like if the Compare At price is lower than the Sale Price, and those sorts of things - so it may just be that there’s an invalid value on a particular field that validates in the shopify dashboard but not in the API.

**Comment by alexleclair** [comment]
Oh! You are totally right! It could absolutely be a `compare_at_price` issue.
If you're feeling adventurous, you could open up `shopify-api-node` in `node_modules` and add a console.log to the value of "body" in [this file](https://github.com/MONEI/Shopify-api-node/blob/master/index.js#L135); it should show what the actual error is, and help solve this :)

**Comment by calebcurtis8** [comment]
Aha! I found it, the fulfillment service is not created in the staging environment so the product cannot be created.
What got me there was adding `console.log(e.response.body)` on line 284 of migrator.js

**Comment by calebcurtis8** [comment]
I was able to fix it for me, but I'm not sure it's a full solution, so I added [at line 172 of migrator.js](https://github.com/workwithpact/StoreDuplicator/blob/4b4a021144a953b18208e6b55f7aa5c071f54e7e/src/migrator.js#L172)
`    /*reset fulfillment services to shopify*/
      delete product.variants[i].fulfillment_service
      product.variants[i].inventory_management = 'shopify'
`

**Comment by alexleclair** [comment]
Very very very good find! That's definitely a good interim solution :-)
